export const DATA_SOURCE_LABELS: Record<string, string> = {
  // 时间
  timeHour: "小时",
  timeHourLow: "小时（低位）",
  timeHourHigh: "小时（高位）",
  timeMinute: "分钟",
  timeMinuteLow: "分钟（低位）",
  timeMinuteHigh: "分钟（高位）",
  timeSecond: "秒",
  timeSecondLow: "秒（低位）",
  timeSecondHigh: "秒（高位）",
  timeCentiSecond: "百分之一秒",
  timeCentiSecondLow: "百分之一秒（低位）",
  timeCentiSecondHigh: "百分之一秒（高位）",
  timeHour12H: "12 小时制小时",
  timeHour24H: "24 小时制小时",
  // 日期
  dateYear: "年",
  dateYearDigit1: "年（第 1 位数字）",
  dateYearDigit2: "年（第 2 位数字）",
  dateYearDigit3: "年（第 3 位数字）",
  dateYearDigit4: "年（第 4 位数字）",
  dateMonth: "月",
  dateMonthLow: "月（低位）",
  dateMonthHigh: "月（高位）",
  dateDay: "日",
  dateDayLow: "日（低位）",
  dateDayHigh: "日（高位）",
  dateWeek: "星期（数字）",
  dateLunarYear: "农历年",
  dateLunarMonth: "农历月",
  dateLunarMonthLow: "农历月（低位）",
  dateLunarMonthHigh: "农历月（高位）",
  dateLunarDay: "农历日",
  dateLunarStringYear: "农历年（字符串）",
  dateLunarStringMonth: "农历月（字符串）",
  dateLunarStringDay: "农历日（字符串）",
  dateWeekStringShortCN: "星期（中文缩写）",
  dateWeekStringFullCN: "星期（中文全称）",
  dateWeekStringFullPascalEN: "星期（英文全称·首字母大写）",
  dateWeekStringFullUpperEN: "星期（英文全称·大写）",
  dateWeekStringFullLowerEN: "星期（英文全称·小写）",
  dateWeekStringShortPascalEN: "星期（英文缩写·首字母大写）",
  dateWeekStringShortUpperEN: "星期（英文缩写·大写）",
  dateWeekStringShortLowerEN: "星期（英文缩写·小写）",
  dateMonthStringShortCN: "月份（中文缩写）",
  dateMonthStringFullPascalEN: "月份（英文全称·首字母大写）",
  dateMonthStringFullUpperEN: "月份（英文全称·大写）",
  dateMonthStringFullLowerEN: "月份（英文全称·小写）",
  dateMonthStringShortPascalEN: "月份（英文缩写·首字母大写）",
  dateMonthStringShortUpperEN: "月份（英文缩写·大写）",
  dateMonthStringShortLowerEN: "月份（英文缩写·小写）",
  dateSexagenaryCycle: "干支纪年",
  dateMoon: "月相",
  dateMoonTomorrow: "月相（明天）",
  dateMoonAfterTomorrow: "月相（后天）",
  dateMoonThreeTomorrow: "月相（三天后）",
  dateMoonFourDaysAgo: "月相（四天前）",
  dateMoonFiveDaysAgo: "月相（五天前）",
  dateMoonSixDaysAgo: "月相（六天前）",
  // 健康
  healthStepCount: "步数",
  healthStepCountDigit1: "步数（第 1 位数字）",
  healthStepCountDigit2: "步数（第 2 位数字）",
  healthStepCountDigit3: "步数（第 3 位数字）",
  healthStepCountDigit4: "步数（第 4 位数字）",
  healthStepCountDigit5: "步数（第 5 位数字）",
  healthStepProgress: "步数进度",
  healthStepKiloMeter: "公里数",
  healthStepTarget: "步数目标",
  healthHeartRate: "心率",
  healthHeartRateZone: "心率区间",
  healthHeartRateMin: "心率（最低）",
  healthHeartRateMax: "心率（最高）",
  healthCalorieValue: "卡路里",
  healthCalorieValueDigit1: "卡路里（第 1 位数字）",
  healthCalorieValueDigit2: "卡路里（第 2 位数字）",
  healthCalorieValueDigit3: "卡路里（第 3 位数字）",
  healthCalorieValueDigit4: "卡路里（第 4 位数字）",
  healthCalorieValueDigit5: "卡路里（第 5 位数字）",
  healthCalorieProgress: "卡路里进度",
  healthCalorieTarget: "卡路里目标",
  healthStandCount: "站立次数",
  healthStandCountDigit1: "站立次数（第 1 位数字）",
  healthStandCountDigit2: "站立次数（第 2 位数字）",
  healthStandProgress: "站立进度",
  healthStandTarget: "站立目标",
  healthOxygenSpO2: "血氧饱和度",
  healthOxygenSpO2Max: "血氧饱和度（最高）",
  healthOxygenSpO2Min: "血氧饱和度（最低）",
  healthPressureIndex: "压力指数",
  healthPressureMax: "压力（最高）",
  healthPressureMin: "压力（最低）",
  healthBloodDiastolicPressureMmhg: "舒张压（mmHg）",
  healthBloodSystolicPressureMmhg: "收缩压（mmHg）",
  healthBloodDiastolicPressureKpa: "舒张压（kPa）",
  healthBloodSystolicPressureKpa: "收缩压（kPa）",
  healthBloodPressureUnit: "血压单位",
  healthSleepDuration: "睡眠时长",
  healthSleepScore: "睡眠评分",
  healthSleepTargetProgress: "睡眠目标进度",
  healthSleepQuality: "睡眠质量",
  healthSleepTarget: "睡眠目标",
  healthExerciseDuration: "运动时长",
  healthExerciseDurationDigit1: "运动时长（第 1 位数字）",
  healthExerciseDurationDigit2: "运动时长（第 2 位数字）",
  healthExerciseDurationDigit3: "运动时长（第 3 位数字）",
  healthExerciseProgress: "运动进度",
  healthExerciseTarget: "运动目标",
  healthEnergyConsumed: "消耗能量",
  healthMiscRecoveryTime: "恢复时间",
  healthMiscRunPowerIndex: "跑步功率指数",
  healthMiscTodayVitalityValue: "今日活力值",
  healthMiscSevenDaysVitalityValue: "七日活力值",
  healthBloodSugarValue: "血糖值",
  healthBloodSugarUpdateTsString: "血糖更新时间",
  healthMenstrualCountdown: "生理期倒计时",
  // 天气
  weatherTemperatureUnit: "温度单位",
  weatherCurrentTemperatureFeel: "体感温度",
  weatherCurrentTemperature: "当前温度",
  weatherCurrentHumidity: "当前湿度",
  weatherCurrentWeather: "当前天气",
  weatherCurrentWindAngle: "当前风向角度",
  weatherCurrentWindSpeed: "当前风速",
  weatherCurrentWindLevel: "当前风力等级",
  weatherCurrentAirQualityIndex: "当前空气质量指数",
  weatherCurrentAirQualityLevel: "当前空气质量等级",
  weatherCurrentChanceOfRain: "当前降雨概率",
  weatherCurrentPressure: "当前气压",
  weatherCurrentVisibility: "当前能见度",
  weatherCurrentUVIndex: "当前紫外线指数",
  weatherCurrentDressIndex: "当前穿衣指数",
  weatherCurrentDrivePlateRestriction: "当前限行",
  weatherCurrentAlert: "当前天气预警",
  weatherCurrentAlertLevel: "当前天气预警等级",
  weatherCurrentUpdateTime: "天气更新时间",
  weatherCurrentWindDirection: "当前风向",
  weatherCurrentSunRiseHour: "日出（时）",
  weatherCurrentSunRiseMinute: "日出（分）",
  weatherCurrentSunSetHour: "日落（时）",
  weatherCurrentSunSetMinute: "日落（分）",
  weatherCurrentTemperatureFahrenheit: "当前温度（华氏）",
  weatherCurrentSunRise: "日出时间",
  weatherCurrentSunSet: "日落时间",
  weatherTodayTemperatureMax: "今日最高温度",
  weatherTodayTemperatureMin: "今日最低温度",
  weatherTodayTemperatureMaxFahrenheit: "今日最高温度（华氏）",
  weatherTodayTemperatureMinFahrenheit: "今日最低温度（华氏）",
  weatherTomorrowTemperatureMax: "明日最高温度",
  weatherTomorrowTemperatureMin: "明日最低温度",
  weatherTomorrowTemperatureMaxFahrenheit: "明日最高温度（华氏）",
  weatherTomorrowTemperatureMinFahrenheit: "明日最低温度（华氏）",
  weatherTomorrowWeatherFrom: "明日天气（起）",
  weatherTomorrowWeatherTo: "明日天气（止）",
  weatherTomorrowWindDirectionFrom: "明日风向（起）",
  weatherTomorrowWindDirectionTo: "明日风向（止）",
  weatherTomorrowWindSpeedFrom: "明日风速（起）",
  weatherTomorrowWindSpeedTo: "明日风速（止）",
  weatherTomorrowAirQualityIndex: "明日空气质量指数",
  weatherTomorrowChanceOfRain: "明日降雨概率",
  // 系统
  systemStatusBattery: "电池电量",
  systemStatusCharge: "充电状态",
  systemStatusDisturb: "勿扰模式",
  systemStatusBluetooth: "蓝牙状态",
  systemStatusWifi: "WiFi 状态",
  systemStatusScreenLock: "屏幕锁定",
  systemStatusVolume: "音量",
  // 传感器
  systemSensorFusionAltitude: "海拔高度",
  systemSensorCompass: "指南针方向",
  systemSensorAtmosphericPressure: "大气压强",
};
