export {
  DEVICE_DEFINITIONS,
  DEVICE_PROFILES,
  DEVICE_PROFILE_MAP,
  DEVICE_SIZES,
  findDeviceProfile,
  getDeviceDefinition,
  getManifestAttributeAllowedValues,
  getDeviceProfile,
  isDataSourceSupported,
  isManifestAttributeSupported,
  isManifestAttributeValueSupported,
  isManifestResourceSupported,
  supportsManifestAttribute,
  manifestAttributeAllowedValues,
  supportsManifestAttributeValue,
  supportsManifestResource,
} from "./registry";
export {
  type DeviceBinaryDefinition,
  type DeviceBinaryHeaderField,
  type DeviceDataSourceDefinition,
  type DeviceDefinition,
  type DeviceDisplayDefinition,
  type DeviceManifestCapabilities,
  type DeviceProfile,
  type DeviceType,
} from "./types";
